<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['dns_alias'] = 'Alias';
$lang['dns_app_description'] = 'Локальный сервер DNS может использоваться для отображения IP-адресов вашей сети и имени узлов.';
$lang['dns_app_name'] = 'DNS Сервер';
$lang['dns_dns_entry'] = 'DNS Запись';
$lang['dns_dns_server'] = 'DNS Сервер';
