<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['dns_alias'] = 'Alias';
$lang['dns_app_description'] = 'Lokalny serwer DNS może być używany do mapowania adresów IP w Twojej sieci z nazwami hostów.';
$lang['dns_app_name'] = 'Serwer DNS';
$lang['dns_dns_entry'] = 'Wpis DNS';
$lang['dns_dns_server'] = 'Serwer DNS';
